### ISSUE TITLE
Feature request : add in upstream

### ISSUE THREAD

**Issue by erdoukki** [gSpotx2f/luci-app-disks-info#1]
Do you plan to add to upstream openwrt ?
Thanks for the works and the share...

**Comment by tournet** [comment]
"page.table is not iterable" error with newest snapshot openwrt.
look forward to seeing update version of luci-app-disks-info.

**Comment by tournet** [comment]
I installed luci-app-disks-info on 2 machines,  luci-app-disks-info works fine on one machine(Intel D2550 +WDC WD20EURS-63S 2TB HDD), but not work on the other, show "page.table is not iterable" error (Intel J1900+HGST HUH721212ALE600 12TB HDD).

**Comment by gSpotx2f** [comment]
@tournet, first of all make a new "Issue", please! Then, show the output of this command: `smartctl -iAHl scttemp -l error -l devstat --json=v /dev/sda` (if "HGST HUH721212ALE600" is /dev/sda). There is a large text, it will be more convenient to use [gist](https://gist.github.com) or [pastebin](https://pastebin.com).
