### ISSUE TITLE
Include NVMe stats

### ISSUE THREAD

**Issue by aphorise** [gSpotx2f/luci-app-disks-info#2]
Hey - Is it possible to include `nvme` drives as well?

```
ls /dev/nvme*
  # /dev/nvme0  /dev/nvme0n1  /dev/nvme0n1p1  /dev/nvme0n1p128  /dev/nvme0n1p2  /dev/nvme0n1p3
```

Not sure if it's related to [luci-app-disks-info/root/usr/share/rpcd/acl.d/luci-app-disks-info.json](https://github.com/gSpotx2f/luci-app-disks-info/blob/master/root/usr/share/rpcd/acl.d/luci-app-disks-info.json#L8-L9) or perhaps something specific to my setup?

PS - Great tools BTW - thank you for all your efforts.

**Comment by gSpotx2f** [comment]
@aphorise, please test [nwme support](https://github.com/gSpotx2f/luci-app-disks-info/commit/963b2f6bef0be4043870399590e50502748e6533). Unfortunately I don't have nwme devices in OpenWrt...

**Comment by aphorise** [comment]
@gSpotx2f thank you once again! - looks fantastic:
![Untitled4](https://user-images.githubusercontent.com/974854/181819272-befa2938-959a-47b8-aa30-ce05337ab432.png)
