### ISSUE TITLE
Increase max limit for logging_interval_value

### ISSUE THREAD

**Issue by remittor** [gSpotx2f/luci-app-disks-info#3]
Fix: https://github.com/openwrt-xiaomi/luci-app-disks-info/commit/a387f205399169d05eeb30f2c6b9143dfca2d863

**Comment by gSpotx2f** [comment]
@remittor [20c9799](https://github.com/gSpotx2f/luci-app-disks-info/commit/20c9799d58718491f48b7546f1bc31f9905277a3)...
