### ISSUE TITLE
Исправление, проверено на версии 23.05.3

### ISSUE THREAD

**Issue by Dronnis** [gSpotx2f/luci-app-disks-info#6]
Здравствуйте внесите исправление, заранее извиняюсь что не pull request(ом) нет возможности его сделать да и исправлял на живой машине.

Исправляет ошибку  
`Cannot read properties of null (reading 'table')`
причина ошибки иногда элементы statObject.pages бывают null 

```
--- /htdocs/luci-static/resources/view/disks-info.js	Thu Jun 13 21:53:17 2024
+++ /htdocs/luci-static/resources/view/disks-info.js	Thu Jun 13 21:54:38 2024
@@ -623,6 +623,7 @@
 			E('h3', {}, _('Device statistics') + ':')
 		);
 		for(let page of statObject.pages) {
+			if(!page) continue;
 			if(!Array.isArray(page.table) || page.table.length === 0) continue;
 			let pageTableTitle = E('h5', { 'style': 'width:100% !important; text-align:left !important' }, _(page.name));
 			let pageTable = E('table', { 'class': 'table' });

```

**Comment by gSpotx2f** [comment]
Спасибо, [исправил](https://github.com/gSpotx2f/luci-app-disks-info/blob/7a9fe960f47fae5e71aa1e8bdb12f40b3453a189/htdocs/luci-static/resources/view/disks-info.js#L626).
