### ISSUE TITLE
Проблема с локализацией страницы статуса.

### ISSUE THREAD

**Issue by radjah** [gSpotx2f/luci-app-disks-info#8]
ID строки в luci-app-disks-info 
https://github.com/gSpotx2f/luci-app-disks-info/blob/master/po/ru/disks-info.po#L212

ID строки в luci-base
https://github.com/openwrt/luci/blob/master/modules/luci-base/po/ru/base.po#L9750

Идентификаторы пересекаются, в итоге получается в шапке таблицы вместо "Начало" ставится "Запустить"
![изображение](https://github.com/user-attachments/assets/e2d8b014-aca4-4291-a7a5-c6e85ff4eee7)

**Comment by gSpotx2f** [comment]
Такие особенности локализации в LuCI. Можно пытаться подбирать оригинальные слова, но они могут встретиться в локализациях других приложений. Наверное правильно было бы чтобы конкретный файл перевода применялся к конкретному приложению, но что есть, то есть.

**Comment by radjah** [comment]
> особенности локализации в LuCI

То есть при замене "Start" на что-от другое пострадает уже английское название?

**Comment by gSpotx2f** [comment]
>То есть при замене "Start" на что-от другое пострадает уже английское название?

Пострадает исходный смысл. Заголовок столбца `Start` взят из вывода утилиты fdisk, там именно так определяется начальный сектор. Английское слово будет то, которое записано в [исходном файле JS](https://github.com/gSpotx2f/luci-app-disks-info/blob/052dc5193fcc97666d12f91d1ac23c5cb5aa72f7/htdocs/luci-static/resources/view/disks-info.js#L126) (это язык по умолчанию). Просто подбирать уникальные слова под перевод, которые не встречаются в других приложениях - это путь в никуда. Все файлы переводов в `/usr/lib/lua/luci/i18n/` (от всех приложений для которых установлены пакеты локализаций) объединяются в одну общую структуру. Если есть повторяющиеся переводы для одного идентификатора (слова или фразы), то остаётся только один из этих переводов.

**Comment by radjah** [comment]
> Если есть повторяющиеся переводы для одного идентификатора (слова или фразы), то остаётся только один из этих переводов.

Ясно, понятно. Печально. :(
